# Build Stage
FROM golang:1.24.3-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o app main.go

# Run Stage
FROM debian:bookworm-slim

# Copy both the app binary and .env file
COPY --from=builder /app/app .
COPY --from=builder /app/.env .

EXPOSE 8081

CMD ["./app"]

